/**
 * Bot command definitions (for the Telegram command menu) and help text.
 */
export const COMMANDS: { command: string; description: string }[] = [
  { command: "start", description: "Welcome, menu & status panel" },
  { command: "menu", description: "Show the menu keyboard" },
  { command: "projects", description: "Projects: list / search <q> / open <path> / new <name>" },
  { command: "sessions", description: "List/resume sessions (active first) \u00b7 /sessions <q>" },
  { command: "active", description: "Sessions running now on the PC" },
  { command: "running", description: "Sessions this chat controls \u2014 switch between them" },
  { command: "killall", description: "Kill all active sessions on the PC" },
  { command: "mcp", description: "Inspect & toggle MCP servers \u00b7 health-check" },
  { command: "tasks", description: "Manage scheduled tasks" },
  { command: "newtask", description: "Create a scheduled task" },
  { command: "history", description: "Show recent conversation history" },
  { command: "new", description: "Start a fresh session here" },
  { command: "status", description: "Current session, project & queue" },
  { command: "usage", description: "Account & context usage" },
  { command: "btw", description: "Run ASAP (now if idle, else next): /btw <text>" },
  { command: "flush", description: "Send queued follow-ups now" },
  { command: "queue", description: "Show queued follow-ups" },
  { command: "cancel", description: "Stop the current turn" },
  { command: "unwatch", description: "Stop following a live session" },
  { command: "model", description: "Switch model: /model <id>" },
  { command: "restart", description: "Restart the Grok agent" },
  { command: "reauth", description: "Sign in to Grok (login or import)" },
  { command: "accounts", description: "Switch between saved Grok accounts" },
  { command: "help", description: "Show help" },
  // Grok Build slash commands (forwarded into the active session)
  { command: "goal", description: "Grok /goal — set/status/pause/resume/clear" },
  { command: "plan", description: "Grok /plan — enter plan mode" },
  { command: "view_plan", description: "Grok /view-plan — show saved plan" },
  { command: "compact", description: "Grok /compact — compress context" },
  { command: "context", description: "Grok /context — context window breakdown" },
  { command: "deep_research", description: "Grok /deep-research <query>" },
  { command: "workflow", description: "Grok /workflow run|pause|resume|stop" },
  { command: "workflows", description: "Grok /workflows — live runs" },
  { command: "remember", description: "Grok /remember <note>" },
  { command: "effort", description: "Grok /effort low|medium|high|xhigh" },
  { command: "session_info", description: "Grok /session-info" },
];

export const HELP_TEXT = [
  "\u{1F916} Grok Telegram Bot",
  "Drive Grok CLI from your phone \u2014 projects, resume, live sessions, diffs.",
  "",
  "HOW IT WORKS",
  "\u2022 Just send a message to chat with Grok in the current project.",
  "\u2022 While Grok is working, anything you send is queued and runs",
  "  automatically when the current turn finishes.",
  "",
  "COMMANDS",
  "/projects \u2014 choose which folder Grok works in",
  "/sessions \u2014 resume one of your recent Grok sessions",
  "/active \u2014 attach to a session currently running on the PC",
  "/history \u2014 show the latest messages of the current session",
  "/new \u2014 start a brand-new session in the current project",
  "/btw <text> \u2014 run it now if idle, otherwise right after the current task",
  "/flush \u2014 run queued follow-ups immediately",
  "/cancel \u2014 stop the current turn",
  "/status \u2014 show session, project and queue size",
  "/reauth \u2014 sign in to Grok (grok login, or import an existing login)",
  "/accounts \u2014 switch between saved Grok accounts",
  "",
  "GROK BUILD SLASH (in the current session)",
  "/goal <objective|status|pause|resume|clear> \u2014 autonomous goal",
  "/plan [description] \u2014 enter plan mode",
  "/view_plan \u2014 show saved plan",
  "/compact [note] \u2014 compress context",
  "/context \u2014 context window usage",
  "/deep_research <query> \u2014 background research workflow",
  "/workflow / /workflows \u2014 workflows",
  "/remember <note> \u2014 save to memory",
  "Other Grok /commands are also forwarded if not a bot command.",
].join("\n");
